### PR TITLE
Weather App website is ready for production

### PR DESCRIPTION
**Pull request by emasdev**
Weather website using openweatherapi in which users can find by city or by geolocation and compare the weather status. Also, you can change how the temperature is displayed, it can be Celsius, Kelvin, Fahrenheit.

### CODE REVIEW

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUESTED🛑🛑🛑🛑**
Hello @emasdev ,
This is a great project implementation. I love the feature of getting the my current location's weather.
However some changes are required to make it impeccable.

[REQUIRED]: The image in the readme file is not the same as the one being displayed. Kindly fix it.
[REQUIRED]: In your read me specify the steps to clone the repo. Remember not everyone is familiar with the steps it takes.
[REQUIRED]: The change of metrics is not working. From celcius to fahrenheit and kelvin is not working. Kindly fix it.
[REQUIRED]: The app doesn't have a webpack configuration. Kindly configure it
[REQUIRED]: Kindly add a package.json to your repo.
[REQUIRED]: I can see that the linters configurations are added to your project but they are not working online. Kindly fix it.

That's it.👍👍👌👌👌
Fix the required changes and ask for another review.
Happy coding💻💻💻💻

**Review by oloomoses — CHANGES_REQUESTED** [review]
## Changes Required :recycle: 
**Hello @emasdev, well done on implementing the changes from the previous review :muscle: 
This project is complete and almost ready for approval. Just minor change is required that shouldn't take you long :point_down:** 

- [x] Ensure that you have the necessary run common commands like build, development should be in package.json inside `scripts' as per the requirements
Screenshot from 2021-03-17 02-05-01
It should look like :arrow_down: 
```javascript
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```

Kindly implement the above changes before submitting another code review.
### If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help
## HAPPY CODING 
_Slack: Oloo Moses_

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @emasdev  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] Your repository is professional when the readme file contains accurate information, currently the following links presented in the readme file are broken: `issues, license links` kindly fix them out!
- [x] The weather app should changes its appearance based on the received data ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png) from Odin)
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by teekaytech — APPROVED** [review]
## Status: Approved :green_circle: 

### Congratulations @emasdev :tada: 

**Thank you for implement all the changes required by the previous reviewers :handshake: 
This project has passed all the mandatory requirements. It is therefore approved :heavy_check_mark:**

You can now merge to the default branch.
Do not forget to fill the project completion form.

**_Good luck with your next task._**

* * * 
**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Pull request merged**
